/** 
 * TODO: load users list
*/
export const LOADUSERSLIST_PENDING = 'LOADUSERSLIST_PENDING'
export const LOADUSERSLIST_SUCCESS = 'LOADUSERSLIST_SUCCESS'
export const LOADUSERSLIST_REJECTED = 'LOADUSERSLIST_REJECTED'

/** 
 * TODO: add users
*/
export const ADDUSERCLICK_DASHBOARDUSER = 'ADDUSERCLICK_DASHBOARDUSER'
export const CLEARADDUSER_DASHBOARDUSER = 'CLEARADDUSER_DASHBOARDUSER'